---
dependencies: []

galaxy_info:
  role_name: attackpath_upload_scripts
  author: bagelByt3s
  description: Upload BloodHound attack path json into Ludus AD environment and create folder structure for ludushound
  company: SpecterOps
  license: GPLv3
  min_ansible_version: "2.10"
  platforms:
    - name: Windows
      versions:
        - "2016"
        - "2019"
        - "2022"

  galaxy_tags:
    - windows
    - security
    - activedirectory
    - server
    - ludus
