---
dependencies: []

galaxy_info:
  role_name: configure_relationship_ou_members_groups
  author: bagelByt3s
  description: Configure group objects to be in the correct OU
  company: SpecterOps
  license: GPLv3
  min_ansible_version: "2.10"
  platforms:
    - name: Windows
      versions:
        - "2016"
        - "2019"
        - "2022"

  galaxy_tags:
    - windows
    - security
    - activedirectory
    - server
    - ludus
