---
dependencies: []

galaxy_info:
  role_name: ludushound
  author: bagelByt3s
  description: Replicate Active Directory settings from BloodHound collection
  company: SpecterOps
  license: GPLv3
  min_ansible_version: "2.10"
  platforms:
    - name: Windows
      versions:
        - "2012R2"
        - "2016"
        - "2019"
        - "2022"

  galaxy_tags:
    - windows
    - security
    - active directory
    - bloodhound
    - server

collections:
  - ansible.windows
  - community.windows
  - community.general
