---
dependencies: []

galaxy_info:
  role_name: attackpath_configure_session
  author: bagelByt3s
  description: Configures computer to have session based on Attack Path Json
  company: SpecterOps
  license: GPLv3
  min_ansible_version: "2.10"
  platforms:
    - name: Windows
      versions:
        - "2016"
        - "2019"
        - "2022"

  galaxy_tags:
    - windows
    - security
    - activedirectory
    - server
    - ludus
