---
dependencies: []

galaxy_info:
  role_name: promote_to_child_dc
  author: bagelByt3s
  description: Promote domain computer to domain controller of child domain
  company: SpecterOps
  license: GPLv3
  min_ansible_version: "2.10"
  platforms:
    - name: Windows
      versions:
        - "2016"
        - "2019"
        - "2022"

  galaxy_tags:
    - windows
    - security
    - activedirectory
    - server
    - ludus
