---
- name: Ensure RSAT tools are installed
  win_feature:
    name: RSAT-AD-PowerShell
    state: present

- name: Import the ActiveDirectory module
  win_shell: |
    Import-Module ActiveDirectory
  args:
    executable: powershell
  register: import_ad_module

- name: Run CreateGroups.ps1 to read the groups.json BloodHound file and create groups
  win_shell: |

    cd c:\windows\tasks\LudusHound\{{ ludushound_domain }}\
    
    powershell -ep bypass c:\Windows\Tasks\LudusHound\Scripts\CreateGroups.ps1 -f .\Groups.json -fullSend

  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ ludus_domain_fqdn }}\{{ defaults.ad_domain_admin }}'
    ansible_become_password: '{{ defaults.ad_domain_admin_password }}'
    ansible_become_flags: "logon_type=interactive logon_flags=with_profile"