---
dependencies: []

galaxy_info:
  role_name: configure_dns_forwarders_child_domains
  author: bagelByt3s
  description: Configure DNS for domains to resolve dns for child domains
  company: SpecterOps
  license: GPLv3
  min_ansible_version: "2.10"
  platforms:
    - name: Windows
      versions:
        - "2016"
        - "2019"
        - "2022"

  galaxy_tags:
    - windows
    - security
    - activedirectory
    - server
    - ludus
