---
## Check and Create C:\Windows\Tasks Directory
- name: Check if C:\Windows\Tasks directory exists
  ansible.builtin.win_stat:
    path: 'C:\Windows\Tasks'
  register: tasks_dir_status

- name: Create C:\Windows\Tasks directory if it doesn't exist
  ansible.builtin.win_file:
    path: 'C:\Windows\Tasks'
    state: directory
  when: not tasks_dir_status.stat.exists

## Check and Create C:\Windows\Tasks\LudusHound Directory
- name: Check if C:\Windows\Tasks\LudusHound directory exists
  ansible.builtin.win_stat:
    path: 'C:\Windows\Tasks\LudusHound'
  register: tasks_ludushound_dir_status

- name: Create C:\Windows\Tasks\LudusHound directory if it doesn't exist
  ansible.builtin.win_file:
    path: 'C:\Windows\Tasks\LudusHound'
    state: directory
  when: not tasks_ludushound_dir_status.stat.exists

## Check and Create C:\Windows\Tasks\LudusHound\AttackPath Directory
- name: Check if C:\Windows\Tasks\LudusHound\AttackPath directory exists
  ansible.builtin.win_stat:
    path: 'C:\Windows\Tasks\LudusHound\AttackPath'
  register: tasks_attackpath_dir_status

- name: Create C:\Windows\Tasks\LudusHound\AttackPath directory if it doesn't exist
  ansible.builtin.win_file:
    path: 'C:\Windows\Tasks\LudusHound\AttackPath'
    state: directory
  when: not tasks_attackpath_dir_status.stat.exists

## Check and Create C:\Windows\Tasks\LudusHound\AttackPath\Scripts Directory
- name: Check if C:\Windows\Tasks\LudusHound\AttackPath\Scripts directory exists
  ansible.builtin.win_stat:
    path: 'C:\Windows\Tasks\LudusHound\AttackPath\Scripts'
  register: tasks_scripts_dir_status

- name: Create C:\Windows\Tasks\LudusHound\AttackPath\Scripts directory if it doesn't exist
  ansible.builtin.win_file:
    path: 'C:\Windows\Tasks\LudusHound\AttackPath\Scripts'
    state: directory
  when: not tasks_scripts_dir_status.stat.exists

## Upload all files from files/* to C:\Windows\Tasks\LudusHound\AttackPath\Scripts
- name: Find all files in the files directory
  ansible.builtin.find:
    paths: "{{ role_path }}/files"
    file_type: file
  register: files_to_upload
  delegate_to: localhost

- name: Upload all files to Scripts directory
  ansible.builtin.win_copy:
    src: "{{ item.path }}"
    dest: 'C:\Windows\Tasks\LudusHound\AttackPath\Scripts\{{ item.path | basename }}'
    remote_src: no
  loop: "{{ files_to_upload.files }}"
  when: files_to_upload.matched > 0