---
dependencies: []

galaxy_info:
  role_name: disable_password_policy
  author: bagelByt3s
  description: Disable password policy
  company: SpecterOps
  license: GPLv3
  min_ansible_version: "2.10"
  platforms:
    - name: Windows
      versions:
        - "2016"
        - "2019"
        - "2022"

  galaxy_tags:
    - windows
    - security
    - activedirectory
    - server
    - ludus
