---
dependencies: []

galaxy_info:
  role_name: configure_relationship_sessions
  author: bagelByt3s
  description: Configure sessions on computer via schtask based on HasSessions.json file
  company: SpecterOps
  license: GPLv3
  min_ansible_version: "2.10"
  platforms:
    - name: Windows
      versions:
        - "2016"
        - "2019"
        - "2022"

  galaxy_tags:
    - windows
    - security
    - activedirectory
    - server
    - ludus
